# .streamlit/secrets.toml

OPENAI_API_KEY = "<your key here>"

[connections.snowflake]
account = "<account>"
user = "<username>"
password = "<password>"
database = "<database>"
schema = "<schema>"
role = "<role>"
warehouse = "<warehouse>"